

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_sp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      # 10s
      connection-timeout: 10000
      # 池中连接最长生命周期 30分钟
      max-lifetime: 1800000
      # 空闲10分钟
      idle-timeout: 600000
      minimum-idle: 16
      maximum-pool-size: 64
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


  application:
    name: spt-order
logging:
  level:
    root: info
    com.gavin.spt.order.dao.mapper: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9400/eureka/,http://localhost:9401/eureka/
