server:
  port: 9400

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9401/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    response-cache-auto-expiration-in-seconds: 60
    renewal-percent-threshold: 0.49